# Generated by Django 5.2.7 on 2025-11-08 02:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_completion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_members',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_date',
            field=models.DateField(default=datetime.date(2025, 11, 8), help_text='Date project was assigned.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Team member assigned to this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 11, 8), help_text='Expected delivery date.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(help_text='Manager who created or owns this project.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
