# Generated by Django 5.2.7 on 2025-11-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='design_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='design_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
