# Generated by Django 5.2.7 on 2025-11-22 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designcomment',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='designcomment',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='designnotification',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='designnotification',
            name='upload',
        ),
        migrations.RenameField(
            model_name='designupload',
            old_name='notes',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='designupload',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.DeleteModel(
            name='DesignApproval',
        ),
        migrations.DeleteModel(
            name='DesignComment',
        ),
        migrations.DeleteModel(
            name='DesignNotification',
        ),
    ]
