# Generated by Django 5.2.7 on 2025-11-24 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_remove_designcomment_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='designupload',
            old_name='link',
            new_name='design_link',
        ),
        migrations.RemoveField(
            model_name='designupload',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='designupload',
            name='file',
        ),
        migrations.AddField(
            model_name='designupload',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AddField(
            model_name='designupload',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_designs', to=settings.AUTH_USER_MODEL),
        ),
    ]
