# Generated by Django 5.2.7 on 2025-11-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Team Member', 'Team Member')], default='Team Member', max_length=20, verbose_name='User Role'),
        ),
    ]
