# Generated by Django 5.2.7 on 2025-11-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_role_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Team Member', 'Team Member'), ('Design Team', 'Design Team'), ('HR', 'HR')], default='Team Member', max_length=20, verbose_name='User Role'),
        ),
    ]
