# Generated by Django 5.2.7 on 2025-11-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_role_selected_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_role_selected',
            field=models.BooleanField(default=False, verbose_name='Has selected role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Team Member', 'Team Member'), ('Design Team', 'Design Team'), ('HR', 'HR')], default='Team Member', max_length=20, null=True, verbose_name='User Role'),
        ),
    ]
